title: Lagi Susah
description: Tempat Download Aplikasi

url: https://lagisusah.github.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: zulfanlife
   twitter: Tidak Ada
   facebook: Tidak Ada
   email: zulfanlife@gmail.com

google_analytics: "Kode Analytics"
